//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICCO.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_empresa
    {
        public tb_empresa()
        {
            this.tb_custo = new HashSet<tb_custo>();
            this.tb_pessoa = new HashSet<tb_pessoa>();
            this.tb_usuario = new HashSet<tb_usuario>();
            this.tb_veiculo = new HashSet<tb_veiculo>();
        }
    
        public int id { get; set; }
        public string nomeFantasia { get; set; }
    
        public virtual ICollection<tb_custo> tb_custo { get; set; }
        public virtual ICollection<tb_pessoa> tb_pessoa { get; set; }
        public virtual ICollection<tb_usuario> tb_usuario { get; set; }
        public virtual ICollection<tb_veiculo> tb_veiculo { get; set; }
    }
}
