//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICCO.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tb_pessoa
    {
        public tb_pessoa()
        {
            this.tb_custo = new HashSet<tb_custo>();
            this.tb_negociacao = new HashSet<tb_negociacao>();
            this.tb_negociacao1 = new HashSet<tb_negociacao>();
            this.tb_usuario = new HashSet<tb_usuario>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "O preenchimento deste campo é obrigatório")]
        public string nome { get; set; }
        [Required(ErrorMessage = "O preenchimento deste campo é obrigatório")]
        public string sobreNome { get; set; }
        [Required(ErrorMessage = "O preenchimento deste campo é obrigatório")]
        public string cpfCnpj { get; set; }
        [Required(ErrorMessage = "O preenchimento deste campo é obrigatório")]
        public string rg { get; set; }
        public string email { get; set; }
        [Required(ErrorMessage = "O preenchimento deste campo é obrigatório")]
        public string cidade { get; set; }
        [Required(ErrorMessage = "O preenchimento deste campo é obrigatório")]
        public string estado { get; set; }
        [Required(ErrorMessage = "O preenchimento deste campo é obrigatório")]
        public string cep { get; set; }
        [Required(ErrorMessage = "O preenchimento deste campo é obrigatório")]
        public string fone { get; set; }
        public string celular { get; set; }
        [Required(ErrorMessage = "O preenchimento deste campo é obrigatório")]
        public string sexo { get; set; }
        [Required(ErrorMessage = "O preenchimento deste campo é obrigatório")]
        public string nascimento { get; set; }
        [Required(ErrorMessage = "O preenchimento deste campo é obrigatório")]
        public string endereco { get; set; }
        public int idEmpresa { get; set; }
        public int idTipoPessoa { get; set; }
    
        public virtual tb_empresa tb_empresa { get; set; }
        public virtual tb_tipopessoa tb_tipopessoa { get; set; }
        public virtual ICollection<tb_custo> tb_custo { get; set; }
        public virtual ICollection<tb_negociacao> tb_negociacao { get; set; }
        public virtual ICollection<tb_negociacao> tb_negociacao1 { get; set; }
        public virtual ICollection<tb_usuario> tb_usuario { get; set; }
    }
}
