//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICCO.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario
    {
        public int id { get; set; }
        public string login { get; set; }
        public string senha { get; set; }
        public int TB_Pessoa_id { get; set; }
        public int TB_Empresa_id { get; set; }
    
        public virtual tb_empresa tb_empresa { get; set; }
        public virtual tb_pessoa tb_pessoa { get; set; }
    }
}
